CC = g++ -std=c++20 -Wall

01.out:01.cpp
	$(CC) -o $@ $*.cpp
02.out:02.cpp
	$(CC) -o $@ $*.cpp
03.out:03.cpp
	$(CC) -o $@ $*.cpp
04.out:04.cpp
	$(CC) -o $@ $*.cpp
05.out:05.cpp
	$(CC) -o $@ $*.cpp
06.out:06.cpp
	$(CC) -o $@ $*.cpp
